version: '3.8'

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol/config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - grafana-lgtm

  grafana-lgtm:
    image: grafana/otel-lgtm
    ports:
      - "3000:3000"
      - "3100:3100"
      - "3200:3200"
