sonar.projectKey=vlimat-backend
sonar.projectName=vlimat-backend
sonar.sources=VLimat.Eduz.App/VLimat.Eduz.App
sonar.tests=VLimat.Eduz.App/VLimat.Eduz.App.Test
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/bin/**,**/obj/**
