name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Sonar Scan and Deploy
    runs-on: self-hosted

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        run: >
          docker run --rm
          -e SONAR_HOST_URL=http://host.docker.internal:9000
          -e SONAR_TOKEN="${{ secrets.SONAR_TOKEN }}"
          -v "${{ github.workspace }}:/usr/src"
          sonarsource/sonar-scanner-cli

      - name: Build Docker Image
        run: docker build -t vlimat-backend:new .

      - name: Stop Existing Container
        run: docker stop vlimat-backend
        continue-on-error: true

      - name: Remove Existing Container
        run: docker rm vlimat-backend
        continue-on-error: true

      - name: Remove Existing Image
        run: docker rmi vlimat-backend
        continue-on-error: true

      - name: Tag New Image
        run: docker tag vlimat-backend:new vlimat-backend

      - name: Run Docker Container
        run: docker run -d --restart unless-stopped -p 5000:8080 --name vlimat-backend vlimat-backend
